name: cd

on:
  issue_comment:
    types: [created]

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@fedjabosnic /apply')

    steps:

    - name: trigger
      env:
        BOT_USER: '${{ secrets.BOT_USER }}'
        BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
        URL_REACTION:  '${{ github.event.comment.url }}/reactions'
        URL_PULL_REQUEST:  '${{ github.event.issue.pull_request.url }}'
      run: |
        HEAD_SHA=$(curl ${URL_PULL_REQUEST} -u ${BOT_USER}:${BOT_TOKEN} | jq -r '.head.sha')
        REACTION=$(curl ${URL_REACTION}     -u ${BOT_USER}:${BOT_TOKEN}' -d {"content": "+1"}' -H 'Accept: application/vnd.github.squirrel-girl-preview+json')
        echo ::set-output name=sha::${HEAD_SHA}
      id: pr
    
    - name: pull code
      uses: actions/checkout@v1
      with:
          ref: ${{ steps.pr.outputs.sha }}

    - name: check
      run : ls
