name: cd

on:
  issue_comment:
    types: [created]

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest

    steps:
    - name: pull code
      uses: actions/checkout@v1

    - uses: khan/pull-request-comment-trigger@master
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      with:
        trigger: '@fedjabosnic apply'
        reaction: '+1'

    - name: print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  apply:
    name: apply
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '@elb2c-bot /apply')

    steps:
    - name: get pull request info
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        GITHUB_CONTEXT: '${{ toJson(github) }}'
      run: |
        pull_request = jq -r ${GITHUB_CONTEXT} '.event.issue.pull_request.url'
        sha = curl ${pull_request} -H 'Authorization: token ${GITHUB_TOKEN}' | jq -r '.head.sha'
        echo '::set-output name=sha::${sha}'
      id: pr
    
    - name: pull code
      uses: actions/checkout@v1
      with:
          ref: ${{ steps.pr.outputs.sha }}

    - name: check
      run : ls
